### ISSUE TITLE
CacheXXXX.bin from W2K8 R2 SP1 / invalid version number.

### ISSUE THREAD

**Issue by llaubin** [ANSSI-FR/bmc-tools#1]
Hi

Running your script on a cacheXX.bin extracted from a W2K8 R2 SP1, it crashed with a div/0 
  File "bmc-tools.py", line 68, in b_process
    cf = t_len/(t_width*t_height)
ZeroDivisionError: long division or modulo by zero

Looking at the code, it's just that the header is not detected as a bin file but a bmc :

C:\temp>hexdump Cache0000.bin 
00000000: 52 44 50 38 62 6D 70 00 - 04 00 00 00 95 E6 95 F9 |RDP8bmp         |
But you check if the file starts with "RDP8bmp\x00\x03\x00\x00\x00" to detect it as a bin file... 

Modifying the \x03 with \x04 is enough to parse and extract the tiles from the cache file. Anyway, you've done a great tool guyz !

**Comment by nitrogenc** [comment]
I pushed the changes; you're right, indeed: this chunk of code was not up-to-date.
As a matter of fact, afaik, this DWORD version field can be 3, 4 or even 6 (on Windows Server 2012 family).
Thanks a lot for reporting the bug! :)
