### ISSUE TITLE
Port to js

### ISSUE THREAD

**Issue by MariasStory** [ANSSI-FR/bmc-tools#11]
HI, thanks for the cool tool.
It would be nice to be able to run the tool in browser.
This way it could be integrated to [CyberChef](https://gchq.github.io/CyberChef/) or run in custom .html solutions.

I see two solutions for this request:
1. Rewrite to .js
2. Run using "pyodide"

I would prefer the first solution, but I also checked the pyodide. It should be easy to run it in the web python with slight modifications.

**Comment by nitrogenc** [comment]
Hi.
This repository is about the Python tool.
If needed in another language, feel free to write the JS code.
