### ISSUE TITLE
Breaks parsing Old Bitmap

### ISSUE THREAD

**Issue by stark4n6** [ANSSI-FR/bmc-tools#13]
Index error on parsing old bitmap data via -o switch
![image](https://user-images.githubusercontent.com/48143894/221965187-bc15362b-2307-42a0-b86f-d8a4cac558f2.png)

**Comment by nitrogenc** [comment]
Hi!
I see exactly what is wrong with what I did! Shame on me!
Should be fixed with commit 4e38d8d.

Thanks for reporting. :)
