### ISSUE TITLE
exported bitmap files aren't saved to --dest as expected

### ISSUE THREAD

**Issue by hiddenillusion** [ANSSI-FR/bmc-tools#2]
Instead of writing files to the full path of the `--dest` parameter, exported files were written to the same directory that the bitmap cache file resided in. 

Here's a quick & tested fix : https://github.com/hiddenillusion/bmc-tools/commit/98d52d170fee02430c0d793592e29ce5795f9fc2

**Comment by nitrogenc** [comment]
Indeed, the full path to the source file should not be computed for the destination filename.
Stripping the path from the `--src` argument will do the math.

Thanks a lot for reporting this issue.
