### ISSUE TITLE
Having an issue with compressed bitmaps

### ISSUE THREAD

**Issue by n00py** [ANSSI-FR/bmc-tools#3]
I'm new to this tool, and I was testing it RDP from Server 2008 -> server 2003.  This is the output:

`C:\Users\Administrator>python bmc-tools.py -d extracted -s "C:\Users\Administrat
or\AppData\Local\Microsoft\Terminal Server Client\Cache" -v
[+++] Processing a directory...
[---] File 'C:\Users\Administrator\AppData\Local\Microsoft\Terminal Server Clien
t\Cache\bcache22.bmc' has been found.
[===] Successfully loaded 'C:\Users\Administrator\AppData\Local\Microsoft\Termin
al Server Client\Cache\bcache22.bmc' as a .BMC container.
[!!!] Tile data is compressed (5632 bytes compressed in 25 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1107 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1276 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 879 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 227 bytes); skipping.
[!!!] Tile data is compressed (5120 bytes compressed in 128 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 1149 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 365 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 1358 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 170 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 101 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 26 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 809 bytes); skipping.
[!!!] Tile data is compressed (5120 bytes compressed in 127 bytes); skipping.
[!!!] Tile data is compressed (5120 bytes compressed in 145 bytes); skipping.
[!!!] Tile data is compressed (5120 bytes compressed in 128 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 752 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 122 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 98 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 24 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (4864 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 433 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 513 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 85 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 288 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 263 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 25 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 27 bytes); skipping.
[!!!] Tile data is compressed (4864 bytes compressed in 25 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1162 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1233 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 21 bytes); skipping.
[!!!] Tile data is compressed (15616 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (4352 bytes compressed in 120 bytes); skipping.
[!!!] Tile data is compressed (4352 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (4352 bytes compressed in 21 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 25 bytes); skipping.
[!!!] Tile data is compressed (15616 bytes compressed in 25 bytes); skipping.
[!!!] Tile data is compressed (7680 bytes compressed in 124 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 1130 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 363 bytes); skipping.
[!!!] Tile data is compressed (5120 bytes compressed in 138 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1505 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1722 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 642 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 852 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 42 bytes); skipping.
[!!!] Tile data is compressed (5120 bytes compressed in 138 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 788 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 130 bytes); skipping.
[!!!] Tile data is compressed (5632 bytes compressed in 44 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1752 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 1369 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 27 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 459 bytes); skipping.
[!!!] Tile data is compressed (16384 bytes compressed in 284 bytes); skipping.
[!!!] Tile data is compressed (4864 bytes compressed in 23 bytes); skipping.
[!!!] Tile data is compressed (4864 bytes compressed in 27 bytes); skipping.
[===] 0 tiles successfully extracted in the end.
[===] Successfully exported 0 files.

C:\Users\Administrator>
`

Is it not possible to extract compressed data?

**Comment by nitrogenc** [comment]
Hi!

Output is perfectly normal as of now.
Decompression is currently being implemented and tested, but I have not much time to work on it right now.
Still, I should be able to release some working version before the end of Summer.

This issue will be kept opened until then.

**Comment by Bostek** [comment]
Having same problem. Will this be sorted out?
btw. Great tool. Would be even greater, if it would have capability to assembly the little bitmaps to one screenshot :)

**Comment by administratorofgithub** [comment]
Hi there @nitrogenc 
Is there any update on this issue? What is the compression algorithm being used?

**Comment by nitrogenc** [comment]
Yeah, it will absolutely be sorted out but I do not know when I will have the time to do it!
As for the re-assembly capability, the aggregate collage bitmap (option "-b") introduced in commit 7a104d78 (version 1.03) should provide some starting point.

Cheers.

**Comment by nterl0k** [comment]
Just wanted to see if there was any update to this issue?  Running into an issue finding a way to parse a compressed BMC from a 2003 device.

Please advise if possible.

**Comment by Sankgreall** [comment]
Hello - is anyone able to provide some guidance on how this compression works, so that we can code our own solutions and/or contribute to this repo? 

There is very little information on this, and it seems to be mostly assumed the algorithm is unknown: https://www.cert.ssi.gouv.fr/actualite/CERTFR-2016-ACT-017/

Unless this is it: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpnsc/949ee2fd-f35f-4cab-be49-e00567554177

**Comment by nitrogenc** [comment]
Hi !

Tile decompression has been implemented today with version 3.00 (commit d7dc673).
All credits from [MS-RDPBCGR] 2.2.9.1.1.3.1.2.4 : https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/b3b60873-16a8-4cbc-8aaa-5f0a93083280

Since the enhancement has been implemented, I'm closing this issue.

Cheers.

**Comment by Sankgreall** [comment]
Fantastic work here.... I'll admit this issue has had me stumped for quite some time. Will be spending today going over your commit to figure out where I was going wrong. Thank you for making the time to add this functionality!
