### ISSUE TITLE
Extracted BMP files can't be opened

### ISSUE THREAD

**Issue by evild3ad** [ANSSI-FR/bmc-tools#4]
Source: Windows Server 2012 R2
bcache*.bmc = 0 Byte
cache????.bin = 104,9 MB

python bmc-tools.py -d /opt/output/ -s /opt/input/ --> not working
python bmc-tools.py -d /opt/output/ -s /opt/input/ -v --> works

6400 files successfully extracted. All files are 17 KB and can't be opened.

**Comment by nitrogenc** [comment]
Hi!

Thanks for the bug report.
Could you post/attach the full output of the "python bmc-tools.py -d /opt/output/ -s /opt/input/ -v" command?

Thanks.

**Comment by mike-bailey** [comment]
For me (all 11KB):
```
[+++] Processing a single file: 'bcache24.bmc'.
[===] Successfully loaded 'bcache24.bmc' as a .BMC container.
[+++] 100 tiles successfully extracted so far.
[+++] 200 tiles successfully extracted so far.
[+++] 300 tiles successfully extracted so far.
[+++] 400 tiles successfully extracted so far.
[+++] 500 tiles successfully extracted so far.
[+++] 600 tiles successfully extracted so far.
[+++] 700 tiles successfully extracted so far.
[+++] 800 tiles successfully extracted so far.
[+++] 900 tiles successfully extracted so far.
[===] 947 tiles successfully extracted in the end.
[===] Successfully exported 947 files.
```

**Comment by nitrogenc** [comment]
Hi, Mike!

Would it be possible for you to provide me this "bcache24.bmc" file?
I have not been able to encounter such a problem, though I tested the tool against a whole lot of data.

Thanks.

**Comment by nitrogenc** [comment]
Closing this issue since nothing new for several years.
