### ISSUE TITLE
Decode issue

### ISSUE THREAD

**Issue by nutastur** [ANSSI-FR/bmc-tools#5]
HI nitrogenc ,
I'm new in Python, so maybe I doing something wrong.
When I run the script the decode error appears.
I think that something is going wrong with utf-8 encoding...
Please help me solve this issue.
I appreciate you help in advance.

C:\Python34>python C:\Python34\bmc-tools.py -s "C:\input\" -d "C:\output\" -v
Traceback (most recent call last):
  File "C:\Python34\bmc-tools.py", line 7, in <module>
    class BMCContainer():
  File "C:\Python34\bmc-tools.py", line 14, in BMCContainer
    PALETTE = "00000000000080000080000000808000800000008000800080800000C0C0C000C0DCC000F0CAA60000204
00000206000002080000020A0000020C0000020E00000400000004020000040400000406000004080000040A0000040C0000
040E00000600000006020000060400000606000006080000060A0000060C0000060E00000800000008020000080400000806
000008080000080A0000080C0000080E00000A0000000A0200000A0400000A0600000A0800000A0A00000A0C00000A0E0000
0C0000000C0200000C0400000C0600000C0800000C0A00000C0C00000C0E00000E0000000E0200000E0400000E0600000E08
00000E0A00000E0C00000E0E00040000000400020004000400040006000400080004000A0004000C0004000E000402000004
02020004020400040206000402080004020A0004020C0004020E00040400000404020004040400040406000404080004040A
0004040C0004040E00040600000406020004060400040606000406080004060A0004060C0004060E00040800000408020004
080400040806000408080004080A0004080C0004080E00040A0000040A0200040A0400040A0600040A0800040A0A00040A0C
00040A0E00040C0000040C0200040C0400040C0600040C0800040C0A00040C0C00040C0E00040E0000040E0200040E040004
0E0600040E0800040E0A00040E0C00040E0E00080000000800020008000400080006000800080008000A0008000C0008000E
00080200000802020008020400080206000802080008020A0008020C0008020E000804000008040200080404000804060008
04080008040A0008040C0008040E00080600000806020008060400080606000806080008060A0008060C0008060E00080800
000808020008080400080806000808080008080A0008080C0008080E00080A0000080A0200080A0400080A0600080A080008
0A0A00080A0C00080A0E00080C0000080C0200080C0400080C0600080C0800080C0A00080C0C00080C0E00080E0000080E02
00080E0400080E0600080E0800080E0A00080E0C00080E0E000C0000000C0002000C0004000C0006000C0008000C000A000C
000C000C000E000C0200000C0202000C0204000C0206000C0208000C020A000C020C000C020E000C0400000C0402000C0404
000C0406000C0408000C040A000C040C000C040E000C0600000C0602000C0604000C0606000C0608000C060A000C060C000C
060E000C0800000C0802000C0804000C0806000C0808000C080A000C080C000C080E000C0A00000C0A02000C0A04000C0A06
000C0A08000C0A0A000C0A0C000C0A0E000C0C00000C0C02000C0C04000C0C06000C0C08000C0C0A000F0FBFF00A4A0A0008
08080000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00".decode("hex")
AttributeError: 'str' object has no attribute 'decode'

**Comment by nitrogenc** [comment]
Hi, nutastur.

Nothing to do with utf-8 encoding: this happens because you are running it with **python 3.x**.
This script is designed to run under **python 2.x**.
python3-support is not a planned feature so I while close this issue.
Though, it is not impossible to have some python3-compatible version in the near future.

Regards,

nitrogenc

**Comment by nitrogenc** [comment]
Issue #9 is about that too.
Python2/3-compatible version is on its way.
Wait for it...

**Comment by nitrogenc** [comment]
With commit 1f623ae BMC-Tools should now be compatible with both Python2 and Python3.
