### ISSUE TITLE
Bug with extracted bitmap size

### ISSUE THREAD

**Issue by brimorlabs** [ANSSI-FR/bmc-tools#8]
Hello!!

First of all, thank you so much for this. I've recommended this to just about everyone who has dealt with RDP Bitmap Cache data, because I have not found anything that processes it nearly as well, fast, or reliable as your script.

As I am working on enhancing my script to automate the rebuilding/pattern matching of the pieces, I came across a bug in your code, with regards to the bitmap header file size. The code understates the size of the outputted bitmap images by a total of four bytes. I think this is because the original math did not account for the "BM" header, plus the two byte file length.

So, lines 201-203 are currently

`return "BM"+pack("<L", len(data)+126)+"\x00\x00\x00\x00\x7A\x00\x00\x00\x6C\x00\x00\x00"+pack("<L", width)+pack("<L", height)+"\x01\x00\x20\x00\x03\x00\x00\x00"+pack("<L", len(data))+"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\x00\x00\xFF\x00\x00\xFF\x00\x00\x00\x00\x00\x00\xFF niW"+("\x00"*36)+"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"+data
		else:
			return "BM"+pack("<L", len(data)+0x36)+"\x00\x00\x00\x00\x36\x04\x00\x00\x28\x00\x00\x00"+pack("<L", width)+pack("<L", height)+"\x01\x00\x08\x00\x00\x00\x00\x00"+pack("<L", len(data)-0x400)+"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"+data
`

and it should be

`return "BM"+pack("<L", len(data)+122)+"\x00\x00\x00\x00\x7A\x00\x00\x00\x6C\x00\x00\x00"+pack("<L", width)+pack("<L", height)+"\x01\x00\x20\x00\x03\x00\x00\x00"+pack("<L", len(data))+"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\x00\x00\xFF\x00\x00\xFF\x00\x00\x00\x00\x00\x00\xFF niW"+("\x00"*36)+"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"+data
		else:
			return "BM"+pack("<L", len(data)+0x32)+"\x00\x00\x00\x00\x36\x04\x00\x00\x28\x00\x00\x00"+pack("<L", width)+pack("<L", height)+"\x01\x00\x08\x00\x00\x00\x00\x00"+pack("<L", len(data)-0x400)+"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"+data
`

Really all that has to be changed is the value of "126" and "0x36" to "122" and "0x32" respectively.

Thank you again, and I hope that helps!

Brian

**Comment by nitrogenc** [comment]
Hi, Brian.

Thanks for your kind words and, more importantly, thanks for your rdpieces tool. :)
I tried a bit to produce some kind of intelligent and efficient rebuilding for the extracted pieces but failed... :P

I had a look at your bug and your proposed fix.
As per the Bitmap file format definition, the 4-byte "size" field following the "BM" header equals to the full size of the Bitmap file, including both the "BM" header and the "size" field.
So, the correct value is easily calculated by testing the length of the returned data without appending the actual "data" variable.

That said, performing some quick tests on the bmc-tools, I ended up with:
- line 201: you're right, correct value is indeed 122 and not 126;
- line 203: the correct value is still 0x36, not 0x32.

Could you give it a try/check on your side if you are okay with that?

I tested with some 64x64 random image in MsPaint, saving it in both "24-bit Bitmap" and "256-color Bitmap" (or "palette Bitmap") format, and getting back the 122 and 0x36 values.

Thanks a lot for your bug report.
I'll wait for your answer and your input before commiting any changes.

Cheers!

--
nitrogenc

**Comment by brimorlabs** [comment]
Yes, you are correct....the original hex value of 0x36 was indeed correct, the only issue resides(ed) on 126. 

Thank you so much, I appreciate the timely response. And again, a big thanks to all of you for all your hard work!

Brian

**Comment by nitrogenc** [comment]
Fixed in 00c2f38.
Thanks for confirming.

And thanks again for the bug report! :)

--
nitrogenc
