### ISSUE TITLE
[Request] Gracefully Exit when using python3

### ISSUE THREAD

**Issue by liamcs98** [ANSSI-FR/bmc-tools#9]
Hey all, small feature request, can we have the program gracefully exit / inform users running it with python 3?

**Comment by nitrogenc** [comment]
Hi. Gonna be honest, you're not the first one to bring up that Python 3 incompatibility stuff.
Let's deal with it the proper way: next commit will make it work for both Python2 and Python3.
Wait for it...

**Comment by nitrogenc** [comment]
With commit 1f623ae BMC-Tools should now be compatible with both Python2 and Python3.
Be patient though if you like collage and Python3...
